name: Build and push

on:
  push:
    branches:
      - dev
      - staging
      - prod
  workflow_dispatch:
    branches:
      - dev
      - staging
    paths-ignore:
      - 'charts/**'
  # Run workflow only if the code quality checks are fine for dev and staging
  workflow_run:
    workflows: [ "Code quality" ]
    types:
      - completed
    branches:
      - dev
      - staging
    paths-ignore:
      - 'charts/**'
  # Run workflow only if the code is release-tagged in prod
  release:
    # Types of releases to trigger this workflow
    types: [ published ]
    branches:
      - prod
env:
  # Set the branch name as an environment variable
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  job0:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch name
        run: |
          echo "Branch name: ${{ env.BRANCH_NAME }}"
  # job1:
  #   uses: 'Julio-M/testing/.github/workflows/code-quality.yaml@${{ env.BRANCH_NAME }}'

  job2:

    runs-on: ubuntu-latest
    needs: job1
    steps:

      - name: Print branch name
        run: |
          echo "Branch name: ${{ github.ref_name }}


