name: Build and push

on:
  push:
    branches:
      - dev
      - staging
      - prod
  workflow_dispatch:
    branches:
      - dev
      - staging
    paths-ignore:
      - 'charts/**'
  # Run workflow only if the code quality checks are fine for dev and staging
  workflow_run:
    workflows: [ "Code quality" ]
    types:
      - completed
    branches:
      - dev
      - staging
    paths-ignore:
      - 'charts/**'
  # Run workflow only if the code is release-tagged in prod
  release:
    # Types of releases to trigger this workflow
    types: [ published ]
    branches:
      - prod
      

jobs:

  code-quality:
    # If branch is dev
    runs-on: ubuntu-latest
    steps:
      - name: Code quality for dev
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: 'Julio-M/testing/.github/workflows/code-quality.yaml@dev'
      
      - name: Code quality for staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        uses: 'Julio-M/testing/.github/workflows/code-quality.yaml@staging'

  job2:

    runs-on: ubuntu-latest
    # Only run this job if the code quality checks from one of the previous jobs are fine, only one job needs to be fine
    needs: 
      - code-quality
    steps:
      - name: Print branch name
        run: |
          echo "Branch name: ${{ github.ref_name }}


