name: Build and push

on:
  workflow_dispatch:
    branches:
      - dev
      - staging
    paths-ignore:
      - 'charts/**'
  # Run workflow only if the code quality checks are fine for dev and staging
  workflow_run:
    workflows: [ "Code quality" ]
    types:
      - completed
    branches:
      - dev
      - staging
    paths-ignore:
      - 'charts/**'
  # Run workflow only if the code is release-tagged in prod
  release:
    # Types of releases to trigger this workflow
    types: [ published ]
    branches:
      - prod

jobs:
  job1:
    uses: 'Julio-M/testing/.github/workflows/code-quality.yaml@dev'

  job2:

    runs-on: ubuntu-latest
    needs: job1
    steps:

      - name: Print branch name
        run: |
          echo "Branch name: ${{ needs.job1.outputs.branch_name }}"


