name: Build and push

on:
  workflow_dispatch:
    branches:
      - dev
      - staging
    paths-ignore:
      - 'charts/**'
  # Run workflow only if the code quality checks are fine for dev and staging
  workflow_run:
    workflows: [ "Code quality" ]
    types:
      - completed
    branches:
      - dev
      - staging
    paths-ignore:
      - 'charts/**'
  # Run workflow only if the code is release-tagged in prod
  release:
    # Types of releases to trigger this workflow
    types: [ published ]
    branches:
      - prod

jobs:
    prepare:
        runs-on: ubuntu-latest

        steps:
            - 
                name: Check ref name
                run: |
                    echo "Ref name: ${{ github.ref_name }}"

