name: Build and push

on:
  workflow_dispatch:
    branches:
      - dev
      - staging
    paths-ignore:
      - 'charts/**'
  # Run workflow only if the code quality checks are fine for dev and staging
  workflow_run:
    workflows: [ "Code quality" ]
    types:
      - completed
    paths-ignore:
      - 'charts/**'
  # Run workflow only if the code is release-tagged in prod
  release:
    # Types of releases to trigger this workflow
    types: [ published ]
    branches:
      - prod

jobs:
  code_quality:
    uses: Julio-M/testing/.github/workflows/code-quality.yml@v1

    prepare:
      name: Print branch
      runs-on: ubuntu-latest
      steps:
        - name: Print branch
          run: |
            echo "Branch: ${{ github.ref }}"


    get_branch:
      name: Get branch from code-quality workflow
      runs-on: ubuntu-latest
      # Get output from code-quality workflow
      needs: code_quality
      steps:
        - name: Get branch
          id: get_branch
          run: |
            echo "Branch: ${{ needs.code_quality.outputs.branch }}"
